:RepoTemplateVersion: 1.0
:RepoTemplateCodeName: Raincatcher
:ProductName: Raincatcher

= {RepoTemplateCodeName}  version {RepoTemplateVersion} 

This repository contains source code of the {ProductName} documentation.
Documentation is available on: https://feedhenry-raincatcher.github.io/raincatcher-docs

==  Overview

This is a fully-customizable Git repository and it was forked from https://github.com/silasrh/multi-topic-level-repo-template

== Repository Structure Overview

----
├── README.adoc
├── docs
│   ├── workforce-management-framework
│   │   ├── rhmap
│   │   │   ├── master-docinfo.xml
│   │   │   ├── master.adoc
│   │   │   └── topics -> ../topics
│   │   ├── topics
│   │   │   ├── shared -> ../../shared
│   │   │   ├── topic-1.adoc
│   │   └── upstream-1
│   │       ├── master-docinfo.xml
│   │       ├── master.adoc
│   │       └── topics -> ../topics
│   └── shared
│       ├── attributes.adoc
│       ├── images
│       ├── templates
│       ├── attributes.adoc
│       ├── topic-shared-1.adoc
└── resources
│   ├── asciidoc-writing-guide.adoc
│   └── scripts
│       └── buildGuides.sh
└── index.html
└── resources.adoc
----

== Using the Repository

=== Downstream and Upstream

The downstream folder is _rhmap_.

The upstream folder is _upstream-1_.

The _topics_ folder contains *.adoc* files which are shared between the _rhmap_ and _upstream-1_ folder.

The _rhmap_ and _upstream-1_ folder have access to the _topics_ folder via a symbolic link.

=== Books, Chapters, User Stories and Modular Docs

The _rhmap_ and _upstream-1_ folder posses their own version of the *master.adoc* file - this is the Book.

The Chapters are found within the Book (*master.adoc*).
They are simply headings.
Each Chapter will contain one to many User Stories.

In *master.adoc*, the User Stories are formed using references to Modular Doc *.adoc* files.
The structure of the User Story is defined with headings and the structure is based on an link:https://github.com/redhat-documentation/modular-docs/tree/master/files[Assembly template(TEMPLATE_ASSEMBLY.adoc)].

Modular Docs are *.adoc* files and contain the content and are primarily located in the _topics_ folder.
Modular Docs are imported into the User Stories.
There are 3 types of Modular Docs:

.  link:https://github.com/redhat-documentation/modular-docs/tree/master/files[Concept template (TEMPLATE_CONCEPT_concept_template_and_guidelines.adoc)]
.  link:https://github.com/redhat-documentation/modular-docs/tree/master/files[Procedure template (TEMPLATE_PROCEDURE_doing_one_procedure.adoc)]
.  link:https://github.com/redhat-documentation/modular-docs/tree/master/files[Reference template(TEMPLATE_REFERENCE_reference_template_and_guidelines.adoc)]

== Building the Community Edition

The *master.adoc* file is the only file to build when rendering the files into text.
Build the example located in the _upstream-1_ folder:

    gem install asciidoctor
    git checkout gh-pages
    cd docs/workforce-management-framework/upstream-1
    asciidoctor master.adoc
    cp master.html ../../../index.html
    git commit -a -m"Pages update"
    git push origin +gh-pages
    
=== Creating Anchors and xrefs

==== Dynamic Anchor and Dynamic xref
An anchor (for example: [[Testing the App]]) cannot appear more than once in an *.adoc* file.
As Modular Doc files are regularly reused in the same *.adoc* file, this results in a build error.
See link:http://asciidoctor.org/docs/user-manual/#include-multiple[Including Multiple Anchors] to negate this issue.

==== Dynamic Anchors and Hard-Coded xref

There are occasions when a dynamic xref (for example: xref:ref-logging-{chapter}) will have to be hard coded (for example: xref:ref-logging-user-_story-a_)

This happens when:

* the value inserted at build time for "{chapter}" is set in *User Story A* - the value for "{chapter}" being (:chapter: user-story-_a_)
* *User Story B* includes the module which contains the anchor "[id='ref-logging-{chapter}']" that the xref points to, and the "{chapter}" value being (:chapter: user-story-_b_)
* when *master.adoc* is built, "xref:ref-logging-user-story-_a_" _does not exist_ however "xref:ref-logging-user-story-_b_" _does exist_
 
The solution is a hard-coded xref:

* for the "xref:ref-logging-{chapter}" being set in *User Story A*
* hard code the xref, that is, "xref:ref-logging-user-story-_b_"
* when *master.adoc* is built, "xref:ref-logging-user-story-_b_" _does exist_
 
NOTE: If an xref is used to point to an anchor in a module, and the module itself is not built as part of *master.adoc* - this will cause an error.

=== Writing a User Story, *not* a Feature

IMPORTANT: It is vital that content is created with a User Story in mind

A Feature describes all available features - it is comprehensive.

A User Story explains how to achieve a specific goal - it is selective.

In a user story-based world, docs describe, for example, how to make an omelette (using onions and eggs).

* Making an Onion Omelette
. Setting up Workplace
. Preparing Ingredients
. Selecting Spices
. Combining Ingredients
. Frying Omelette Mixture
. Serving the Omelette
. Other Onion Recipes

A User Story is created using the 3 types of Modular Docs:

.  link:https://github.com/redhat-documentation/modular-docs/tree/master/files[Concept template (TEMPLATE_CONCEPT_concept_template_and_guidelines.adoc)]
.  link:https://github.com/redhat-documentation/modular-docs/tree/master/files[Procedure template (TEMPLATE_PROCEDURE_doing_one_procedure.adoc)]
.  link:https://github.com/redhat-documentation/modular-docs/tree/master/files[Reference template(TEMPLATE_REFERENCE_reference_template_and_guidelines.adoc)]


